### ISSUE TITLE
TWITTER_ERROR: Request failed with status code 404

### ISSUE THREAD

**Issue by NeronSignal** [Rishikant181/Rettiwt-API#703]
I'm encountering a 404 error when trying to search for tweets using the following query:
`{
  "includeWords": ["NEWS", "#DOGE"],
  "hasImages": true,
  "hasVideos": false,
  "top": true
}`

'TWITTER_ERROR: Request failed with status code 404'

**Comment by Rishikant181** [comment]
That's a known issue because of the way a header (`x-client-transaction-id`) is generated. TL;DR is, the header is very time sensitive (nano-second time). Usually, a retry or two will return the expected result. I've also pushed out a fix in `v5.0.1` which aims to reduce the occurrence of this error. Let me know if that works.

On a side note, there are no params called `hasImages` or `hasVideos`, though that's not the root of the issue.

**Comment by NeronSignal** [comment]
Hi,

Thanks for the quick response and explanation! A few follow-up questions: 
Is v5.0.1 currently available for installation? I’m currently using alpha5.
Understood about hasImages/hasVideos—those are my custom variables (not part of the API params).

I’ll retry on failures as suggested. Appreciate the fix!

**Comment by Rishikant181** [comment]
@NeronSignal 

> Is v5.0.1 currently available for installation? I’m currently using alpha5

Yes

> Understood about hasImages/hasVideos—those are my custom variables (not part of the API params)

Got it. Does Twitter provide anything like that or is it just a post-fetch filter?

**Comment by NeronSignal** [comment]
No, Twitter doesn't support that natively. I'm just analyzing the output and filtering out unwanted videos myself.

**Comment by Alvie** [comment]
> That's a known issue because of the way a header (`x-client-transaction-id`) is generated. TL;DR is, the header is very time sensitive (nano-second time). Usually, a retry or two will return the expected result. I've also pushed out a fix in `v5.0.1` which aims to reduce the occurrence of this error. Let me know if that works.
> 
> On a side note, there are no params called `hasImages` or `hasVideos`, though that's not the root of the issue.

Hi, I am using v5.0.1 but I am still getting this error a lot with streaming

**Comment by Rishikant181** [comment]
@Alvie The only workaround seems to be adding a retry mechanism in case of error 404, with a delay of 1 second in between successive retries.

The endpoint actually exists and functional, but I guess it's the `x-client-transaction` header not being accurate 100% of the time. So retry usually works around it.

**Comment by Alvie** [comment]
> [@Alvie](https://github.com/Alvie) The only workaround seems to be adding a retry mechanism in case of error 404, with a delay of 1 second in between successive retries.
> 
> The endpoint actually exists and functional, but I guess it's the `x-client-transaction` header not being accurate 100% of the time. So retry usually works around it.

Thanks, yeah, I have it catching and calling itself when it gets an error

**Comment by Rishikant181** [comment]
@Alvie Try `v6.0.0` which adds a `maxRetries` parameter while configuring `Rettiwt`. By default, `Rettiwt` assumes `maxRetries` value of 5, with a `delay` of 1000ms, if none of those are defined during configuration. You can override it by setting the values manually. Try experimenting with it to get a sweet spot.

**Comment by Rishikant181** [comment]
@Alvie I just implemented the use of an external library for the transaction id generation, and it seems to have reduced the frequency of/removed altogether the error 404.

During my personal testing, never once did I end up getting error 404 again.

Please update to `v6.0.2`.

Since the errors has been mitigated, the defaults for `maxRetries` and `delay` have been set back to 0. If anyhow error 404 still pops up, a singe retry should fix it.

**Comment by Rishikant181** [comment]
Duplicate of #691

**Comment by Alvie** [comment]
> [@Alvie](https://github.com/Alvie) I just implemented the use of an external library for the transaction id generation, and it seems to have reduced the frequency of/removed altogether the error 404.
> 
> During my personal testing, never once did I end up getting error 404 again.
> 
> Please update to `v6.0.1`.
> 
> Since the errors has been mitigated, the defaults for `maxRetries` and `delay` have been set back to 0. If anyhow error 404 still pops up, a singe retry should fix it.

Awesome, thank you, I'll give it a shot! You're doing amazing work mate, much appreciated

**Comment by Rishikant181** [comment]
@Alvie Slight correction, it's `v6.0.2`. `6.0.1` had a broken dependency when published to npm.
